// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmuLUW8U79BZsjtP-En9lwn3pZvDU0tFA',
    appId: '1:1025398049693:web:300e2ce7caf36917457d74',
    messagingSenderId: '1025398049693',
    projectId: 'my-app-quiz',
    authDomain: 'my-app-quiz.firebaseapp.com',
    storageBucket: 'my-app-quiz.appspot.com',
    measurementId: 'G-EHR8XR6QVX',
    databaseURL: "https://my-app-quiz-default-rtdb.firebaseio.com",  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY2gAvaQTuurI8p1ax_N8gzc6MeFimUaA',
    appId: '1:1025398049693:android:68e476c143285ec6457d74',
    messagingSenderId: '1025398049693',
    projectId: 'my-app-quiz',
    storageBucket: 'my-app-quiz.appspot.com',
      databaseURL: "https://my-app-quiz-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Gn9DPYU2DsV_OnePgtm6QXVL49X4ulU',
    appId: '1:1025398049693:ios:9f82b725c09e7c8b457d74',
    messagingSenderId: '1025398049693',
    projectId: 'my-app-quiz',
    storageBucket: 'my-app-quiz.appspot.com',
    iosClientId: '1025398049693-ta8nclk8m6cgarp5ge67k01m18v0280f.apps.googleusercontent.com',
    iosBundleId: 'com.secit.ahmedsherif.qzapp.qiuzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Gn9DPYU2DsV_OnePgtm6QXVL49X4ulU',
    appId: '1:1025398049693:ios:1a2bb4ea49ae3231457d74',
    messagingSenderId: '1025398049693',
    projectId: 'my-app-quiz',
    storageBucket: 'my-app-quiz.appspot.com',
    iosClientId: '1025398049693-md5bptcfjlhilkicu9ins60eul0ujgdk.apps.googleusercontent.com',
    iosBundleId: 'com.secit.ahmedsherif.qzapp.quiz',
  );
}
